//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraiteurBernardWPF.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TraiteurBernardWPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actif.
        /// </summary>
        internal static string Actif {
            get {
                return ResourceManager.GetString("Actif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actif &amp; Inactif.
        /// </summary>
        internal static string ActifInactif {
            get {
                return ResourceManager.GetString("ActifInactif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Toutes les tournées.
        /// </summary>
        internal static string AllTournees {
            get {
                return ResourceManager.GetString("AllTournees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à contre-tournée.
        /// </summary>
        internal static string CT {
            get {
                return ResourceManager.GetString("CT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dessert midi.
        /// </summary>
        internal static string DessertMidi {
            get {
                return ResourceManager.GetString("DessertMidi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dessert soir.
        /// </summary>
        internal static string DessertSoir {
            get {
                return ResourceManager.GetString("DessertSoir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrée midi.
        /// </summary>
        internal static string EntreeMidi {
            get {
                return ResourceManager.GetString("EntreeMidi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrée soir.
        /// </summary>
        internal static string EntreeSoir {
            get {
                return ResourceManager.GetString("EntreeSoir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à C:\\eixa6\\circle.png.
        /// </summary>
        internal static string imgCircle {
            get {
                return ResourceManager.GetString("imgCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Assets/TourneeMidiContre.png.
        /// </summary>
        internal static string ImgTourneeCT {
            get {
                return ResourceManager.GetString("ImgTourneeCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Assets/TourneeSoirContre.png.
        /// </summary>
        internal static string ImgTourneeCTSoir {
            get {
                return ResourceManager.GetString("ImgTourneeCTSoir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Assets/TourneeMidiMarennes.png.
        /// </summary>
        internal static string ImgTourneeMarennes {
            get {
                return ResourceManager.GetString("ImgTourneeMarennes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Assets/TourneeSoirMarennes.png.
        /// </summary>
        internal static string ImgTourneeMarennesSoir {
            get {
                return ResourceManager.GetString("ImgTourneeMarennesSoir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Assets/TourneeMidiVille.png.
        /// </summary>
        internal static string ImgTourneeVille {
            get {
                return ResourceManager.GetString("ImgTourneeVille", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Assets/TourneeSoirVille.png.
        /// </summary>
        internal static string ImgTourneeVilleSoir {
            get {
                return ResourceManager.GetString("ImgTourneeVilleSoir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à C:\\eixa6\\trait.png.
        /// </summary>
        internal static string imgTrait {
            get {
                return ResourceManager.GetString("imgTrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inactif.
        /// </summary>
        internal static string Inactif {
            get {
                return ResourceManager.GetString("Inactif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Marennes.
        /// </summary>
        internal static string Marennes {
            get {
                return ResourceManager.GetString("Marennes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le fichier traiteur.db est copié de local au nas.
        /// </summary>
        internal static string MessageLogCopyFichierDbLocalToNas {
            get {
                return ResourceManager.GetString("MessageLogCopyFichierDbLocalToNas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le fichier de base de données a été copié du local vers le dossier nas.
        /// </summary>
        internal static string MessageLogCopyLocalToNas {
            get {
                return ResourceManager.GetString("MessageLogCopyLocalToNas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le fichier de base de données a été copié du nas vers le dossier local.
        /// </summary>
        internal static string MessageLogCopyNasToLocal {
            get {
                return ResourceManager.GetString("MessageLogCopyNasToLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deuxième sauvegarde sur le nas OK.
        /// </summary>
        internal static string MessageLogDeuxiemeSauvegarde {
            get {
                return ResourceManager.GetString("MessageLogDeuxiemeSauvegarde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le fichier traiteur.db n&apos;existe pas sur le nas il coupe l&apos;application.
        /// </summary>
        internal static string MessageLogFichierDbPasSurNasIlCoupe {
            get {
                return ResourceManager.GetString("MessageLogFichierDbPasSurNasIlCoupe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le fichier traiteur.db n&apos;existe pas sur le nas mais il travail en local.
        /// </summary>
        internal static string MessageLogFichierDbPasSurNasTravailEnLocal {
            get {
                return ResourceManager.GetString("MessageLogFichierDbPasSurNasTravailEnLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le fichier traiteur.db est enregistré en local pas sur le nas.
        /// </summary>
        internal static string MessageLogFichierDbSaveLocalPasNas {
            get {
                return ResourceManager.GetString("MessageLogFichierDbSaveLocalPasNas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le fichier lock existe..
        /// </summary>
        internal static string MessageLogFichierLockExiste {
            get {
                return ResourceManager.GetString("MessageLogFichierLockExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le fichier lock n&apos;existe pas, il est créé..
        /// </summary>
        internal static string MessageLogFichierLockExistePas {
            get {
                return ResourceManager.GetString("MessageLogFichierLockExistePas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le fichier lock est présent il quitte l&apos;application..
        /// </summary>
        internal static string MessageLogFichierLockKo {
            get {
                return ResourceManager.GetString("MessageLogFichierLockKo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le fichier lock est présent il force le lancement de l&apos;application..
        /// </summary>
        internal static string MessageLogFichierLockOk {
            get {
                return ResourceManager.GetString("MessageLogFichierLockOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le fichier traiteur.db est bien sauvegardé sur le nas.
        /// </summary>
        internal static string MessageLogSauvegardeLocalToNas {
            get {
                return ResourceManager.GetString("MessageLogSauvegardeLocalToNas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le fichier nas.xml n&apos;est pas présent il coupe l&apos;application pour paramétrer le nas.xml..
        /// </summary>
        internal static string MessageLogXmlNoLocal {
            get {
                return ResourceManager.GetString("MessageLogXmlNoLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le fichier nas.xml n&apos;est pas présent il travaille en local..
        /// </summary>
        internal static string MessageLogXmlYesLocal {
            get {
                return ResourceManager.GetString("MessageLogXmlYesLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le fichier de données est enregistré sur le NAS..
        /// </summary>
        internal static string MessagePopUpCopyFichierDbLocalToNas {
            get {
                return ResourceManager.GetString("MessagePopUpCopyFichierDbLocalToNas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le fichier de données a été récupéré sur le NAS..
        /// </summary>
        internal static string MessagePopUpCopyLocalToNas {
            get {
                return ResourceManager.GetString("MessagePopUpCopyLocalToNas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le fichier de données a été récupéré sur le NAS..
        /// </summary>
        internal static string MessagePopUpCopyNasToLocal {
            get {
                return ResourceManager.GetString("MessagePopUpCopyNasToLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous êtes sur le point de supprimer ce compte de facturation, voulez vous continuer ?.
        /// </summary>
        internal static string MessagePopUpDelFacturation {
            get {
                return ResourceManager.GetString("MessagePopUpDelFacturation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous êtes sur le point de supprimer ce menu, voulez vous continuer ?.
        /// </summary>
        internal static string MessagePopUpDelMenu {
            get {
                return ResourceManager.GetString("MessagePopUpDelMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible de générer un PDF avec des données incomplètes.
        /// </summary>
        internal static string MessagePopUpDonnes {
            get {
                return ResourceManager.GetString("MessagePopUpDonnes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Problème avec le fichier de données ! Contacter EIXA6 Informatique.
        /// </summary>
        internal static string MessagePopUpEixa6Alerte {
            get {
                return ResourceManager.GetString("MessagePopUpEixa6Alerte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Données manquantes..
        /// </summary>
        internal static string MessagePopUpErrorDonnes {
            get {
                return ResourceManager.GetString("MessagePopUpErrorDonnes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La semaine et la personne sont indispensables et la semaine doit être impaire et pas supérieure à 53..
        /// </summary>
        internal static string MessagePopUpErrorIndiIncorrecte {
            get {
                return ResourceManager.GetString("MessagePopUpErrorIndiIncorrecte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;année, la semaine et la personne sont indispensables.
        /// </summary>
        internal static string MessagePopUpErrorIndispensable {
            get {
                return ResourceManager.GetString("MessagePopUpErrorIndispensable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le numéro de la semaine et le numéro du jour sont indispensables.
        /// </summary>
        internal static string MessagePopUpErrorIndispensable2 {
            get {
                return ResourceManager.GetString("MessagePopUpErrorIndispensable2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le nom, le prénom et le numéro de téléphone sont indispensables.
        /// </summary>
        internal static string MessagePopUpErrorIndispensable3 {
            get {
                return ResourceManager.GetString("MessagePopUpErrorIndispensable3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le numéro de la semaine doit être inférieur ou égal à 52.
        /// </summary>
        internal static string MessagePopUpErrorSemaineSup52 {
            get {
                return ResourceManager.GetString("MessagePopUpErrorSemaineSup52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Un autre utilisateur travaille sur le fichier de base de données. Voulez-vous quand même travailler sur le même fichier ? Un risque de tout perdre est envisageable..
        /// </summary>
        internal static string MessagePopUpFicherLockExiste {
            get {
                return ResourceManager.GetString("MessagePopUpFicherLockExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Informations indispensables.
        /// </summary>
        internal static string MessagePopUpInfoIndispensable {
            get {
                return ResourceManager.GetString("MessagePopUpInfoIndispensable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Informations indispensables ou incorrectes.
        /// </summary>
        internal static string MessagePopUpInfoIndispensableIncorrecte {
            get {
                return ResourceManager.GetString("MessagePopUpInfoIndispensableIncorrecte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le mois est indispensable..
        /// </summary>
        internal static string MessagePopUpMois {
            get {
                return ResourceManager.GetString("MessagePopUpMois", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous n&apos;avez pas accès au NAS voulez-vous travailler en local ?.
        /// </summary>
        internal static string MessagePopUpNasExistePas {
            get {
                return ResourceManager.GetString("MessagePopUpNasExistePas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le nom est indispensable.
        /// </summary>
        internal static string MessagePopUpNomIndi {
            get {
                return ResourceManager.GetString("MessagePopUpNomIndi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La semaine de fin doit être supérieure ou égale à la semaine de début.
        /// </summary>
        internal static string MessagePopUpS2SuperieurS1 {
            get {
                return ResourceManager.GetString("MessagePopUpS2SuperieurS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le fichier de données est enregistré sur le NAS.
        /// </summary>
        internal static string MessagePopUpSauvegardeLocalToNas {
            get {
                return ResourceManager.GetString("MessagePopUpSauvegardeLocalToNas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Semaine incorrecte.
        /// </summary>
        internal static string MessagePopUpSemaine {
            get {
                return ResourceManager.GetString("MessagePopUpSemaine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous ne pouvez prendre un numéro de semaine supérieur à 52. Choisissez une autre semaine.
        /// </summary>
        internal static string MessagePopUpSemaineHorsAnnee {
            get {
                return ResourceManager.GetString("MessagePopUpSemaineHorsAnnee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous devez renseigner une semaine de début et une semaine de fin.
        /// </summary>
        internal static string MessagePopUpSemaines {
            get {
                return ResourceManager.GetString("MessagePopUpSemaines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La tournée est indispensable..
        /// </summary>
        internal static string MessagePopUpTournee {
            get {
                return ResourceManager.GetString("MessagePopUpTournee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous devez selectioner le type de personnes (Actif/Inactif).
        /// </summary>
        internal static string MessagePopUpTypeIndi {
            get {
                return ResourceManager.GetString("MessagePopUpTypeIndi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le fichier de configuration du nas n&apos;est pas créé voulez-vous travailler en local?.
        /// </summary>
        internal static string MessagePopUpXml {
            get {
                return ResourceManager.GetString("MessagePopUpXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez configurer le fichier nas.xml.
        /// </summary>
        internal static string MessagePopUpXmlNoLocal {
            get {
                return ResourceManager.GetString("MessagePopUpXmlNoLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Plat 1 midi.
        /// </summary>
        internal static string Plat1Midi {
            get {
                return ResourceManager.GetString("Plat1Midi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Plat 2 midi.
        /// </summary>
        internal static string Plat2Midi {
            get {
                return ResourceManager.GetString("Plat2Midi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Plat 3 midi.
        /// </summary>
        internal static string Plat3Midi {
            get {
                return ResourceManager.GetString("Plat3Midi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Plat soir.
        /// </summary>
        internal static string PlatSoir {
            get {
                return ResourceManager.GetString("PlatSoir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Alerte.
        /// </summary>
        internal static string TitrePopUpAlerte {
            get {
                return ResourceManager.GetString("TitrePopUpAlerte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmation.
        /// </summary>
        internal static string TitrePopUpConfirmation {
            get {
                return ResourceManager.GetString("TitrePopUpConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Information.
        /// </summary>
        internal static string TitrePopUpInfo {
            get {
                return ResourceManager.GetString("TitrePopUpInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ville 1.
        /// </summary>
        internal static string Ville1 {
            get {
                return ResourceManager.GetString("Ville1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ville 2.
        /// </summary>
        internal static string Ville2 {
            get {
                return ResourceManager.GetString("Ville2", resourceCulture);
            }
        }
    }
}
